"""add_command_logs_and_schema_updates

Revision ID: af4a1369067c
Revises: ca5c806d7e5e
Create Date: 2026-03-27 19:21:05.807815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4a1369067c'
down_revision: Union[str, None] = 'ca5c806d7e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=50), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('camera_settings', sa.Column('camera_source', sa.String(length=10), nullable=False, server_default='mipi'))
    op.add_column('camera_settings', sa.Column('output_width', sa.Integer(), nullable=False, server_default='1920'))
    op.add_column('camera_settings', sa.Column('output_height', sa.Integer(), nullable=False, server_default='1080'))
    op.add_column('camera_settings', sa.Column('stream_running', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('camera_settings', 'stream_key')
    op.add_column('cameras', sa.Column('pending_command', sa.String(length=50), nullable=True))
    op.alter_column('cameras', 'camera_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_column('companies', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('slug', sa.VARCHAR(length=50), nullable=False))
    op.alter_column('cameras', 'camera_key',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('cameras', 'pending_command')
    op.add_column('camera_settings', sa.Column('stream_key', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('camera_settings', 'stream_running')
    op.drop_column('camera_settings', 'output_height')
    op.drop_column('camera_settings', 'output_width')
    op.drop_column('camera_settings', 'camera_source')
    op.drop_table('command_logs')
    # ### end Alembic commands ###
