"""add cameras settings and status

Revision ID: ca5c806d7e5e
Revises: bc2371064dc1
Create Date: 2026-03-26 08:36:09.684040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5c806d7e5e'
down_revision: Union[str, None] = 'bc2371064dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('camera_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_key')
    )
    op.create_table('camera_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('stream_key', sa.String(length=500), nullable=True),
    sa.Column('settings_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id')
    )
    op.create_table('camera_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('stream_running', sa.Boolean(), nullable=False),
    sa.Column('stream_width', sa.Integer(), nullable=True),
    sa.Column('stream_height', sa.Integer(), nullable=True),
    sa.Column('stream_fps', sa.Float(), nullable=True),
    sa.Column('stream_bitrate', sa.Integer(), nullable=True),
    sa.Column('stream_time', sa.String(length=20), nullable=True),
    sa.Column('stream_quality', sa.String(length=20), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('gpu_usage', sa.Float(), nullable=True),
    sa.Column('mem_used', sa.Integer(), nullable=True),
    sa.Column('mem_total', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.Float(), nullable=True),
    sa.Column('disk_total', sa.Float(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_status')
    op.drop_table('camera_settings')
    op.drop_table('cameras')
    # ### end Alembic commands ###
